### ISSUE TITLE
Document our approach to NumPy arrays

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [secondmind-labs/trieste#127]
As a user, I want to know whether Trieste supports NumPy arrays, and if so, what guarantees it has about compatibility (e.g. test coverage).

As a maintainer, I want to know what level of support I should include for NumPy arrays (e.g. should source code support it, should i test for it)

These questions need answering and documenting, probably on the trieste homepage

**Comment by joelberkeley-secondmind** [comment]
Does `tf.function` work differently with `np.ndarray` and `tf.Tensor`?

**Comment by joelberkeley-secondmind** [comment]
@vpicheny and I decided informally to support NumPy arrays in the code, but not make any guarantees about them. In particular, we won't test with NumPy arrays

**Comment by uri-granta** [comment]
We have gradually migrated to only supporting tensors not numpy arrays (though in some cases passing in a numpy array will still work). The `TensorType` alias used for type checking now refers to just `tf.Tensor` and `tf.Variable`. This was done because maintaining code that supported both was found to be too awkard (and wasn't helped by the limited type stubs which meant mypy didn't pick up many errors).
