### ISSUE TITLE
Module privacy is inconsistent

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#135]
The acquisition rule module depends on acquisition functions, and currently has to import those the from the actual `function` module. The function module therefore needs to be visible, but is currently hidden (by omitting the module docstring). A similar problem may be present for the `models` package.

Task: Find and implement a consistent import tree and approach to docs visibility that is convenient and intuitive to users

**Comment by uri-granta** [comment]
I don't think this an issue anymore. The function modules _do_ have docstrings and _are_ visible in the docs. (Also, docstring references typically refer to the reexported API versions: i.e. trieste.acquisition.ExpectedImprovement rather than trieste.acquisition.functions.ExpectedImprovement or trieste.acquisition.function.function.ExpectedImprovement.)
