### ISSUE TITLE
Consider CodeQL for scanning vulnerabilities

### ISSUE THREAD

**Issue by joelberkeley** [secondmind-labs/trieste#154]
As a user, I want to know Trieste doesn't expose my software or hardware to vulnerabilities, so that I can use it with confidence in sensitive contexts.

[CodeQL](https://securitylab.github.com/tools/codeql) is one way of achieving this. PR #146 gives an example of how to apply it.

**Comment by uri-granta** [comment]
@jamesrobson-secondmind I believe you looked at this originally. Is this something we are still interested in?

**Comment by jamesrobson-secondmind** [comment]
At the time it didn't seem very useful, I'm not sure if they've made improvements since then. There's also things like https://www.sonarsource.com/products/sonarcloud/ which are free for open source projects. 
The Trieste project needs to decide how concerned you are about potential security vulnerabilities, then consider what tools will help you most.

**Comment by uri-granta** [comment]
Closing CodeQL-specific ticket. Will discuss our general approach to security vulnerabilities elsewhere.
