### ISSUE TITLE
implement `__eq__` on `trieste.data.Dataset` class

### ISSUE THREAD

**Issue by tensorlicious** [secondmind-labs/trieste#195]
**Describe the feature you'd like**
`__eq__` should be implemented on `trieste.data.Dataset` to allow easy comparison of Datasets.  This is useful for testing.

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
Currently use two `tf.debugging.assert_near` calls on query points and observations to compare two `Dataset` objects.

**Additional context**

**Comment by joelberkeley** [comment]
How about instead we make trieste's test utility `assert_datasets_allclose` part of the public API via a `testing` module?

I'd certainly prefer this over adding `__eq__`. I'm wary of bloating the API with functionality not clearly required for BO.

If we did add a new method, what does it mean for points to be equal? For testing purposes, we're often only interested in approximate equality due to floating point error. In contrast, tensors and array only compares equal for exact equality, and as a user I'd intuit the same for datasets.

**Comment by tensorlicious** [comment]
I take your point about ambiguity in the meaning of 'equal' for floating point-based data structures.  Exposing `assert_datasets_allclose` via a `testing` module sounds reasonable to me iff testing for `Dataset` equality is just something that never comes up in non-test code.

**Comment by joelberkeley** [comment]
I can't think of any cases where we've wanted to compare datasets outside tests, so I suggest we go with `assert_datasets_allclose`. This was always my intention with the testing utilities: to eventually move them to the public API for downstream library tests.

**Comment by uri-granta** [comment]
This has indeed never come up outside our tests, and I haven't yet seen a strong case to make it public, so having `assert_datasets_allclose` in `tests.util` is probably enough for now.
