### ISSUE TITLE
Implement `get_hypercell_bounds ` method 

### ISSUE THREAD

**Issue by TsingQAQ** [secondmind-labs/trieste#197]
**Describe the feature you'd like**
a `get_hypercell_bounds` functionality (for multi-objective optimization) to get partitioned cell bounds. (instead of the idx)
Which can be directly applicable for the use of hyper-volume related calculation.

**Additional context**
See [this code](https://github.com/TsingQAQ/trieste/blob/92fc6e35cc5d0dc850e09e42a72d19fba93a834f/trieste/acquisition/multiobjective/analytic.py#L136) and  [this code](https://github.com/pytorch/botorch/blob/44f3000da7ff633631b5d3384a0d509c656dc4e2/botorch/acquisition/multi_objective/analytic.py#L144) as a usage reference

**Comment by satrialoka** [comment]
We have two option for this:

1. keep the `BoundedVolumes` and add `get_hypercell_bounds` 
2. replace `BoundedVolumes`  entirely and only store the value of the bounds

currently the `BoundedVolumes`  store the index of partition w.r.t the pseudo pareto front `pf_ext`.  different partition method will have different hyper-cell bound.  I personally prefer to keep storing the index so it is easy to keep track whats happening in the partition w.r.t to `pf_ext`. if we don't store the index it might be hard to debug IMO. so I personally prefer option 1.

**Comment by joelberkeley** [comment]
If the indices are only ever used in algorithms to create the bounds, I'm in favour of hiding the indices. Exposing functionality costs maintenance and flexibility.

**Comment by satrialoka** [comment]
Do you sometimes needs the indices in the acquisition function @TsingQAQ ? if it is the case seems option 2 is more preferable for a long term.  I just thinking again about this and browse trough some of my acquisition function implementation on gpflowopt, and yeah seems hiding the indices is not a problem at all.

**Comment by TsingQAQ** [comment]
@satrialoka  up until now cannot come up with a scenario when I need the indices having cell bounds already. 
The only question is just which class should hold this functionality, cause the cell bounds is partition algorithm correlated.

**Comment by satrialoka** [comment]
To resolve this, I am thinking to replace the index stored in `BoundedVolumes` with  the bounds values, and add `size` method which is needed for the n>2 objective box decomposition method. **or** we can instead back to store the bounds values in trieste's `Box` and calculate the `size` directly inside the  n>2 objective box decomposition method.

**Comment by joelberkeley** [comment]
am i right in thinking that in a single `BoundedVolumes` you're storing N pairs of (lower, upper) bounds like [lower1, lower2, ... lowerN] and [upper1, upper2, ... upperN] for N pareto points? If so, `Box` isn't designed like that and it's probably not a good idea to change that without some serious thought as it's quite central. Perhaps this was your original concern with using `Box` @satrialoka ?

**Comment by satrialoka** [comment]
Ah yeah, sorry i forgot that.
So, the bounds also can be more than N. For example, if we use box decomposition method which produce grid N*N (this was the most naive way to calculate it though)

**Comment by satrialoka** [comment]
It seems directly store the value of the bound to `BoundedVolumes` is not so trivial. because the first element of the bound list can take a different value depending on the case. 
For example, in the hypervolume case, the first bound is the [minimum of each objective in the front](https://github.com/secondmind-labs/trieste/blob/66f6d84daa004d934d9534f2e49899972abc4d88/trieste/utils/pareto.py#L135). while in the acquisition function it can be [-inf](https://github.com/TsingQAQ/trieste/blob/92fc6e35cc5d0dc850e09e42a72d19fba93a834f/trieste/utils/pareto.py#L321) (correct me if I am wrong). 
Also, the last element of the bound list is the reference point that we provide when calling hypervolume or calculating the acquisition function. so it's not directly available when we run the box decomposition method (`_bounds_2d` for example). 
for now, what I am doing is adding `get_hypercell_bounds` on the `BoundedVolume ` while keeping the index stored in there.
please see a draft PR for this in [here](https://github.com/satrialoka/trieste/commit/0e904a307be3505e4a10d27317815a7c633d56dc)

I am still thinking if it is possible to hide the index. one option is doing what botorch is doing, by having two functions. the first one is a function that returns the [index](https://github.com/pytorch/botorch/blob/44f3000da7ff633631b5d3384a0d509c656dc4e2/botorch/utils/multi_objective/box_decompositions/non_dominated.py#L251), the second is a function that returns the [value](https://github.com/pytorch/botorch/blob/44f3000da7ff633631b5d3384a0d509c656dc4e2/botorch/utils/multi_objective/box_decompositions/non_dominated.py#L289)

**Comment by satrialoka** [comment]
@joelberkeley do you have any comment on this? we need this function for EHVI implementation.

**Comment by joelberkeley** [comment]
I'm sorry I'm not available right now. Is it possible to put the implementation for `get_hypercell_bounds` in @TsingQAQ 's PR? It can be a draft PR so doesn't need to be ready

**Comment by satrialoka** [comment]
okay :ok_hand:

**Comment by TsingQAQ** [comment]
@joelberkeley @satrialoka Please find the [draft PR](https://github.com/secondmind-labs/trieste/pull/202/files#diff-771609eaf758f710f70d659b130548de123e9c914b1f58de14d5ecfaebd08443) which has this function implemented for your reference.
