### ISSUE TITLE
Improve monitoring support

### ISSUE THREAD

**Issue by uri-granta** [secondmind-labs/trieste#401]
Since https://github.com/secondmind-labs/trieste/pull/370 we have basics support for monitoring scalar metrics using Tensorboard. It would be good to:

* add more default scalar metrics
* make customising metrics simpler, both adding new ones and disabling existing ones
* log experiment configuration details (including toolbox version) to the same directory
* investigate any other non-scalar metrics (histograms?) or logs we may wish to monitor
* investigate visualising computation graph

**Comment by henrymoss** [comment]
We would also like textual logging with Tensorboard (https://www.tensorflow.org/tensorboard/text_summaries)

For example, https://github.com/secondmind-labs/trieste/issues/440

**Comment by vpicheny** [comment]
When we do greedy batch acquisitions, we log `EGO.acquisition_function.maximum_found` for each point in the batch, which makes the tensorboard cluttered with rather useless info. 

A simple fix could be to group these by name so they appear as a single line? Alternatively, we could decide to not log this quantity for batches by default, or only if the batch size is smaller than, say, 5.

**Comment by vpicheny** [comment]
We currently don't log the query points. And we only log the best observation of the batch (which is convenient because it becomes a scalar, but then we don't have the full information). This is possibly the most important stuff, so we definitely need to do something.

For batch-one strategies, we may want to record the query points (as a series of scalars, grouped under "query point" name). 

For batches, we could record each component still, provided that we can group them neatly to avoid having a very large tensorboard. We might want to cap the number of plots? e.g. if `input_dim * num_query_points > 20` (I put 20 a bit randomly, depends on how it looks perhaps) we don't log those values.

A nice way of representing query points is using `pairplots`. We could consider logging these, with say different colours for the past observations and the new batch. Maybe this incurs some overhead, in that case we should make it optional?

Lastly, for large batches (say, >10) the way to go could be histograms, for each coordinate of the query points and for the new observations, see the image attached. 

![image](https://user-images.githubusercontent.com/9933795/154260745-9c4a886d-210f-4ed8-b398-781cdcfafc92.png)

**Comment by vpicheny** [comment]
minor point: `OBJECTIVE.observation.best_new` is not straightforward to understand, replace by `(...).best_in_batch`?

**Comment by hstojic** [comment]
I would also add some metadata, e.g. run info like num initial points, budget size, batch size, model and acq rule/function used with all the arguments

when we have several runs and want to compare them its easy to lose sense on which exps was done with what variant

**Comment by uri-granta** [comment]
The initial suggestion (pairplots, metadata, etc) have all been implemented. Suggest closing this after https://github.com/secondmind-labs/trieste/pull/577 is checked in (though we may obviously do more work on logging in the future).

**Comment by hstojic** [comment]
I agree, we can close this one and open new ones once we have concrete suggestions
