### ISSUE TITLE
Support `callback` function for `BayesianOptimizer`

### ISSUE THREAD

**Issue by TsingQAQ** [secondmind-labs/trieste#489]
**Describe the feature you'd like**
In applications, the user may favor a `callback` function (which can take inputs including `models`, `datasets`, `acquisition_state`) for `BayesianOptimizer.optimize()`. This can be useful for several reasons:
1.  get current best (as well as its input) for some intermediate performance check.
2.  easily define some other online inspecting strategies besides the current quantities logged.
2.  optimal stopping: stop the bo process before the `num_steps` if some stopping rule defined in `callback` has been met.

**Comment by hstojic** [comment]
Thanks for the suggestion!

These are fair points.
3. I was thinking about this point previously, perhaps a callback is a good solution to that
2. Re logging we are aware current system is not flexible enough, we opted for gathering feedback for some time and then update it with something more flexible. Personally, I like metrics system in Keras.
1. If user needs to do a lot of additional processing between optimization steps probably AskTell interface should be used instead of the BayesianOptimizer

Overall, I think we could introduce support for callbacks and support the stopping rule to begin with
@vpicheny, @henrymoss and @uri-granta what do you think?

**Comment by TsingQAQ** [comment]
Many thanks for the insightful explanation!
Regarding the 3rd point, [there](https://github.com/TsingQAQ/trieste/blob/22613cb98c722d8ac0feadfb2b26fd20417c24ce/trieste/bayesian_optimizer.py#L472-L481) is a draft solution (not fully tackled mypy test yet) hopefully demonstrate more what am thinking on this point.

**Comment by uri-granta** [comment]
I've implemented this in #579 (alongside an example `stop_at_minimum` callback). Thanks for the suggestion!
