### ISSUE TITLE
typing error not caught?

### ISSUE THREAD

**Issue by hstojic** [secondmind-labs/trieste#509]
@sebastianober noted that in search spaces dimension is commonly defined as 
```
@property
    def dimension(self) -> int:
        """The number of inputs in this search space."""
        return self._dimension
```
now, even though the output is actually a tensor, as  it is always computed as 
```
self._dimension = tf.shape(self._upper)[-1]
```
no typing error is reported by mypy?

**Comment by uri-granta** [comment]
This is because there aren't currently any typing stubs for tensorflow (also numpy, but those are at least available in more recent versions). Hence mypy treats `self._dimension` as being of type `Any` and can't tell whether or not it's a valid int.

I'm afraid there's not much we can do about this at the moment, apart from rely on unit tests and observations to identify these sort of issues, and fix them as soon as we find them (e.g. in `DiscreteSearchSpace` and `Box`).

As an aside, `test_spaces.Integers` doesn't return typing errors for `dimension`, `lower` and `upper` because an implementation with just a `pass` (or `...`) is assumed to be a function stub rather than an actual implementation: https://mypy.readthedocs.io/en/latest/stubs.html#stub-file-syntax

**Comment by hstojic** [comment]
ok, wasn't aware of that

I can raise a PR for correcting dimension, should we keep the integers or change the type to tensor?

**Comment by sebastianober** [comment]
I would guess that changing the type to tensor would be the simplest solution, since if we want to keep it as an int we should probably change `self._dimension` to actually store an int, which might break things elsewhere.
